# Generated by Django 4.1.1 on 2022-09-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('image', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Изображение')),
                ('categories', models.CharField(choices=[('OTHER', 'Разное'), ('ELECTRONICS', 'Электроника'), ('SPORT', 'Спорт'), ('COMPUTERS', 'Компьютеры'), ('CLOTHES', 'Одежда'), ('CAR', 'Автотовары')], default='OTHER', max_length=100, verbose_name='Категория')),
                ('remainder', models.PositiveIntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
    ]
