# Generated by Django 4.1.1 on 2022-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('OTHER', 'Разное'), ('FURNITURE', 'Мебель'), ('SPORT', 'Спорт'), ('COMPUTERS', 'Компьютеры'), ('CLOTHES', 'Одежда'), ('CAR', 'Автотовары')], default='OTHER', max_length=100, verbose_name='Категория'),
        ),
    ]
