# Generated by Django 4.1.1 on 2022-09-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('OTHER', 'Other'), ('FURNITURE', 'Furniture'), ('SPORT', 'Sport'), ('COMPUTERS', 'Computer'), ('CLOTHES', 'Clothes'), ('AUTOPRODUCT', 'Auto product')], default='OTHER', max_length=100, verbose_name='Категория'),
        ),
    ]
