# Generated by Django 4.1.1 on 2022-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0012_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='market_app.OrderProduct', to='market_app.product', verbose_name='Products'),
        ),
    ]
